from flask import Flask, jsonify, request
from flask_restx import Api, Resource
from src.server.instance import server
from src.services.text_to_image_service import *

import json

app, api = server.app, server.api


@api.route('/text-to-image')
class TextToImageController(Resource):
    """
    This method brings a image generated by parti-pytorch method from a input text describing a image.
    """
    @api.doc(params={
        'text': {'in': 'query', 'description': 'The text describing the image', 'type': 'string'}
    })
    def get(self):
        data = request.args
        try:
            print("text:", data['text'])
            image = text_to_image_service.generate_with_diffusers([data['text']])[0]
            return json.dumps(str(image)), 200
        except Exception as e:
            print('Error', e)
            return json.dumps(e), 400
